### ISSUE TITLE
Perl Installation Issue

### ISSUE THREAD

**Issue by heyplaceme** [elastic/elasticsearch-perl#74] opened 2015-06-25 14:44 UTC
i couldn't install the perl module (Search::Elasticsearch) in Ubuntu 14.04.2 LTS. kindly help me how to proceed

error message
--------------------------------------
    root@ip-213-12-42-32:~# cpan install Search::Elasticsearch
    Reading '/home/rim/.cpan/Metadata'
      Database was generated on Thu, 25 Jun 2015 05:17:02 GMT
    Running install for module 'Search::Elasticsearch'
    Running make for D/DR/DRTECH/Search-Elasticsearch-1.20.tar.gz
    Checksum for /home/rim/.cpan/sources/authors/id/D/DR/DRTECH/Search-Elasticsearch-1.20.tar.gz ok

      CPAN.pm: Building D/DR/DRTECH/Search-Elasticsearch-1.20.tar.gz

    Checking if your kit is complete...
    Looks good
    Writing Makefile for Search::Elasticsearch
    Writing MYMETA.yml and MYMETA.json
    cp lib/Search/Elasticsearch/Role/Serializer/JSON.pm blib/lib/Search/Elasticsearch/Role/Serializer/JSON.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct/Nodes.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct/Nodes.pm
    cp lib/Search/Elasticsearch/Cxn/HTTPTiny.pm blib/lib/Search/Elasticsearch/Cxn/HTTPTiny.pm
    cp lib/Search/Elasticsearch/Role/Is_Sync.pm blib/lib/Search/Elasticsearch/Role/Is_Sync.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct/Nodes.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct/Nodes.pm
    cp lib/Search/Elasticsearch/Client/Direct.pm blib/lib/Search/Elasticsearch/Client/Direct.pm
    cp lib/Search/Elasticsearch/Serializer/JSON/XS.pm blib/lib/Search/Elasticsearch/Serializer/JSON/XS.pm
    cp lib/Search/Elasticsearch/TestServer.pm blib/lib/Search/Elasticsearch/TestServer.pm
    cp lib/Search/Elasticsearch/Serializer/JSON/Cpanel.pm blib/lib/Search/Elasticsearch/Serializer/JSON/Cpanel.pm
    cp lib/Search/Elasticsearch/Cxn/Hijk.pm blib/lib/Search/Elasticsearch/Cxn/Hijk.pm
    cp lib/Search/Elasticsearch/Role/Client/Direct.pm blib/lib/Search/Elasticsearch/Role/Client/Direct.pm
    cp lib/Search/Elasticsearch/Role/CxnPool/Sniff.pm blib/lib/Search/Elasticsearch/Role/CxnPool/Sniff.pm
    cp lib/Search/Elasticsearch/CxnPool/Sniff.pm blib/lib/Search/Elasticsearch/CxnPool/Sniff.pm
    cp lib/Search/Elasticsearch/Util/API/Path.pm blib/lib/Search/Elasticsearch/Util/API/Path.pm
    cp lib/Search/Elasticsearch/Role/CxnPool/Static/NoPing.pm blib/lib/Search/Elasticsearch/Role/CxnPool/Static/NoPing.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct/Indices.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct/Indices.pm
    cp lib/Search/Elasticsearch/Role/Client.pm blib/lib/Search/Elasticsearch/Role/Client.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct/Indices.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct/Indices.pm
    cp lib/Search/Elasticsearch/Serializer/JSON/PP.pm blib/lib/Search/Elasticsearch/Serializer/JSON/PP.pm
    cp lib/Search/Elasticsearch/Bulk.pm blib/lib/Search/Elasticsearch/Bulk.pm
    cp lib/Search/Elasticsearch/Role/Logger.pm blib/lib/Search/Elasticsearch/Role/Logger.pm
    cp lib/Search/Elasticsearch/Client/0_90/Direct.pm blib/lib/Search/Elasticsearch/Client/0_90/Direct.pm
    cp lib/Search/Elasticsearch/Client/0_90/Direct/Cluster.pm blib/lib/Search/Elasticsearch/Client/0_90/Direct/Cluster.pm
    cp lib/Search/Elasticsearch/Role/Cxn.pm blib/lib/Search/Elasticsearch/Role/Cxn.pm
    cp lib/Search/Elasticsearch/Role/Transport.pm blib/lib/Search/Elasticsearch/Role/Transport.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct/Snapshot.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct/Snapshot.pm
    cp lib/Search/Elasticsearch/Cxn/Factory.pm blib/lib/Search/Elasticsearch/Cxn/Factory.pm
    cp lib/Search/Elasticsearch/Role/API/1_0.pm blib/lib/Search/Elasticsearch/Role/API/1_0.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct/Cat.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct/Cat.pm
    cp lib/Search/Elasticsearch/Cxn/LWP.pm blib/lib/Search/Elasticsearch/Cxn/LWP.pm
    cp lib/Search/Elasticsearch/Serializer/JSON.pm blib/lib/Search/Elasticsearch/Serializer/JSON.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct/Cluster.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct/Cluster.pm
    cp lib/Search/Elasticsearch/Role/API/2_0.pm blib/lib/Search/Elasticsearch/Role/API/2_0.pm
    cp lib/Search/Elasticsearch/Transport.pm blib/lib/Search/Elasticsearch/Transport.pm
    cp lib/Search/Elasticsearch/Scroll.pm blib/lib/Search/Elasticsearch/Scroll.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct.pm
    cp lib/Search/Elasticsearch/Logger/LogAny.pm blib/lib/Search/Elasticsearch/Logger/LogAny.pm
    cp lib/Search/Elasticsearch/Client/0_90/Direct/Indices.pm blib/lib/Search/Elasticsearch/Client/0_90/Direct/Indices.pm
    cp lib/Search/Elasticsearch.pm blib/lib/Search/Elasticsearch.pm
    cp lib/Search/Elasticsearch/Error.pm blib/lib/Search/Elasticsearch/Error.pm
    cp lib/Search/Elasticsearch/Client/2_0/Direct.pm blib/lib/Search/Elasticsearch/Client/2_0/Direct.pm
    cp lib/Search/Elasticsearch/Role/Scroll.pm blib/lib/Search/Elasticsearch/Role/Scroll.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct/Cat.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct/Cat.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct/Cluster.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct/Cluster.pm
    cp lib/Search/Elasticsearch/Role/Bulk.pm blib/lib/Search/Elasticsearch/Role/Bulk.pm
    cp lib/Search/Elasticsearch/Client/1_0/Direct/Snapshot.pm blib/lib/Search/Elasticsearch/Client/1_0/Direct/Snapshot.pm
    cp lib/Search/Elasticsearch/Util.pm blib/lib/Search/Elasticsearch/Util.pm
    cp lib/Search/Elasticsearch/Role/CxnPool.pm blib/lib/Search/Elasticsearch/Role/CxnPool.pm
    cp lib/Search/Elasticsearch/Role/API/0_90.pm blib/lib/Search/Elasticsearch/Role/API/0_90.pm
    cp lib/Search/Elasticsearch/CxnPool/Static.pm blib/lib/Search/Elasticsearch/CxnPool/Static.pm
    cp lib/Search/Elasticsearch/Role/CxnPool/Static.pm blib/lib/Search/Elasticsearch/Role/CxnPool/Static.pm
    cp lib/Search/Elasticsearch/CxnPool/Static/NoPing.pm blib/lib/Search/Elasticsearch/CxnPool/Static/NoPing.pm
    cp lib/Search/Elasticsearch/Role/Cxn/HTTP.pm blib/lib/Search/Elasticsearch/Role/Cxn/HTTP.pm
    cp lib/Search/Elasticsearch/Util/API/QS.pm blib/lib/Search/Elasticsearch/Util/API/QS.pm
    cp lib/Search/Elasticsearch/Role/Client/Direct/Main.pm blib/lib/Search/Elasticsearch/Role/Client/Direct/Main.pm
    cp lib/Search/Elasticsearch/Role/Serializer.pm blib/lib/Search/Elasticsearch/Role/Serializer.pm
    Manifying blib/man3/Search::Elasticsearch::Role::API::1_0.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct::Snapshot.3pm
    Manifying blib/man3/Search::Elasticsearch::Logger::LogAny.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::API::2_0.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::0_90::Direct::Indices.3pm
    Manifying blib/man3/Search::Elasticsearch::Transport.3pm
    Manifying blib/man3/Search::Elasticsearch::CxnPool::Static::NoPing.3pm
    Manifying blib/man3/Search::Elasticsearch::CxnPool::Static.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Serializer.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Scroll.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Client::Direct::Main.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct::Cat.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct.3pm
    Manifying blib/man3/Search::Elasticsearch::Error.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct::Cluster.3pm
    Manifying blib/man3/Search::Elasticsearch::Serializer::JSON.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::API::0_90.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct::Cat.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::CxnPool.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Bulk.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Cxn::HTTP.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct::Cluster.3pm
    Manifying blib/man3/Search::Elasticsearch::Util::API::QS.3pm
    Manifying blib/man3/Search::Elasticsearch.3pm
    Manifying blib/man3/Search::Elasticsearch::Util.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::CxnPool::Sniff.3pm
    Manifying blib/man3/Search::Elasticsearch::Bulk.3pm
    Manifying blib/man3/Search::Elasticsearch::Cxn::Hijk.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::0_90::Direct::Cluster.3pm
    Manifying blib/man3/Search::Elasticsearch::Serializer::JSON::XS.3pm
    Manifying blib/man3/Search::Elasticsearch::Serializer::JSON::Cpanel.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct::Nodes.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Client.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Is_Sync.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Serializer::JSON.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct::Nodes.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::1_0::Direct::Indices.3pm
    Manifying blib/man3/Search::Elasticsearch::Scroll.3pm
    Manifying blib/man3/Search::Elasticsearch::Cxn::LWP.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::CxnPool::Static.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::Direct.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Client::Direct.3pm
    Manifying blib/man3/Search::Elasticsearch::TestServer.3pm
    Manifying blib/man3/Search::Elasticsearch::CxnPool::Sniff.3pm
    Manifying blib/man3/Search::Elasticsearch::Cxn::Factory.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::CxnPool::Static::NoPing.3pm
    Manifying blib/man3/Search::Elasticsearch::Util::API::Path.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::0_90::Direct.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Logger.3pm
    Manifying blib/man3/Search::Elasticsearch::Serializer::JSON::PP.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct::Snapshot.3pm
    Manifying blib/man3/Search::Elasticsearch::Cxn::HTTPTiny.3pm
    Manifying blib/man3/Search::Elasticsearch::Client::2_0::Direct::Indices.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Cxn.3pm
    Manifying blib/man3/Search::Elasticsearch::Role::Transport.3pm
      DRTECH/Search-Elasticsearch-1.20.tar.gz
      /usr/bin/make -- OK
    Running make test
    PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/10_Basic/*.t t/20_Serializer/*.t t/30_Logger/*.t t/40_Transport/*.t t/50_Cxn_Pool/*.t t/60_Cxn/*.t t/70_Helper/*.t t/90_Client_Spec/*.t
    t/10_Basic/10_load.t .......................... ok   
    t/20_Serializer/10_load_cpanel.t .............. ok   
    t/20_Serializer/11_load_xs.t .................. ok   
    t/20_Serializer/12_load_pp.t .................. ok   
    t/20_Serializer/13_preload_cpanel.t ........... skipped: Cpanel::JSON::XS not installed
    t/20_Serializer/14_preload_xs.t ............... ok   
    t/20_Serializer/20_xs_encode_decode.t ......... ok    
    t/20_Serializer/21_xs_encode_bulk.t ........... ok    
    t/20_Serializer/22_xs_encode_pretty.t ......... ok    
    t/20_Serializer/30_cpanel_encode_decode.t ..... skipped: Cpanel::JSON::XS not installed
    t/20_Serializer/31_cpanel_encode_bulk.t ....... skipped: Cpanel::JSON::XS not installed
    t/20_Serializer/32_cpanel_encode_pretty.t ..... skipped: Cpanel::JSON::XS not installed
    t/20_Serializer/40_pp_encode_decode.t ......... ok    
    t/20_Serializer/41_pp_encode_bulk.t ........... ok    
    t/20_Serializer/42_pp_encode_pretty.t ......... ok    
    t/30_Logger/10_explicit.t ..................... 1/? Current cxns: ["http://localhost:9200"]
    Forcing ping before next use on all live cxns
    Ping [http://localhost:9200] before next request
    t/30_Logger/10_explicit.t ..................... ok    
    t/30_Logger/20_implicit.t ..................... 1/? Current cxns: ["http://localhost:9200"]
    Forcing ping before next use on all live cxns
    Ping [http://localhost:9200] before next request
    t/30_Logger/20_implicit.t ..................... ok   
    t/30_Logger/30_log_methods.t .................. ok    
    t/30_Logger/40_trace_request.t ................ ok    
    t/30_Logger/50_trace_response.t ............... ok   
    t/30_Logger/60_trace_error.t .................. ok   
    t/30_Logger/70_trace_comment.t ................ ok   
    t/40_Transport/10_tidy_request.t .............. ok    
    t/40_Transport/20_send_body_as.t .............. ok   
    t/40_Transport/30_perform_request.t ........... ok   
    t/50_Cxn_Pool/10_static_normal.t .............. ok   
    t/50_Cxn_Pool/11_static_node_missing.t ........ ok   
    t/50_Cxn_Pool/12_static_node_fails.t .......... ok   
    t/50_Cxn_Pool/13_static_node_timesout.t ....... ok   
    t/50_Cxn_Pool/14_static_both_nodes_timeout.t .. ok   
    t/50_Cxn_Pool/15_static_both_nodes_fail.t ..... ok   
    t/50_Cxn_Pool/16_static_nodes_starting.t ...... ok   
    t/50_Cxn_Pool/17_static_runaway_nodes.t ....... ok   
    t/50_Cxn_Pool/30_sniff_normal.t ............... ok   
    t/50_Cxn_Pool/31_sniff_new_nodes.t ............ ok   
    t/50_Cxn_Pool/32_sniff_node_fails.t ........... ok   
    t/50_Cxn_Pool/33_sniff_both_nodes_fail.t ...... ok   
    t/50_Cxn_Pool/34_sniff_node_timeout.t ......... ok   
    t/50_Cxn_Pool/35_sniff_both_nodes_timeout.t ... ok   
    t/50_Cxn_Pool/36_sniff_nodes_starting.t ....... ok   
    t/50_Cxn_Pool/37_sniff_runaway_nodes.t ........ ok   
    t/50_Cxn_Pool/38_bad_sniff.t .................. ok   
    t/50_Cxn_Pool/39_sniff_max_content.t .......... ok   
    t/50_Cxn_Pool/50_noping_normal.t .............. ok   
    t/50_Cxn_Pool/51_noping_node_fails.t .......... ok   
    t/50_Cxn_Pool/52_noping_node_timesout.t ....... ok   
    t/50_Cxn_Pool/53_noping_all_nodes_fail.t ...... ok   
    t/50_Cxn_Pool/54_noping_nodes_starting.t ...... ok   
    t/50_Cxn_Pool/55_noping_runaway_nodes.t ....... ok   
    t/50_Cxn_Pool/56_max_retries.t ................ ok   
    t/50_Cxn_Pool/70_live.t ....................... skipped: No Elasticsearch test node available
    t/60_Cxn/10_basic.t ........................... ok    
    t/60_Cxn/20_process_response.t ................ ok    
    t/60_Cxn/30_http.t ............................ ok     
    t/60_Cxn/40_fork_httptiny.t ................... skipped: No Elasticsearch test node available
    t/60_Cxn/41_fork_lwp.t ........................ skipped: No Elasticsearch test node available
    t/60_Cxn/42_fork_hijk.t ....................... skipped: No Elasticsearch test node available
    t/60_Cxn/50_auth_httptiny.t ................... skipped: HTTPTiny - No https server specified in ES_SSL
    t/60_Cxn/51_auth_lwp.t ........................ skipped: LWP - No https server specified in ES_SSL
    t/70_Helper/10_bulk_add_action.t .............. skipped: No Elasticsearch test node available
    t/70_Helper/20_bulk_helpers.t ................. skipped: No Elasticsearch test node available
    t/70_Helper/30_bulk_flush.t ................... skipped: No Elasticsearch test node available
    t/70_Helper/40_bulk_errors.t .................. skipped: No Elasticsearch test node available
    t/70_Helper/45_bulk_cxn_errors.t .............. 1/? 
    #   Failed test 'threw Search::Elasticsearch::Error::NoNodes'
    #   at t/70_Helper/45_bulk_cxn_errors.t line 31.
    # expecting: Search::Elasticsearch::Error::NoNodes
    # found: normal exit

    #   Failed test 'Buffer count post-flush'
    #   at t/70_Helper/45_bulk_cxn_errors.t line 32.
    #          got: '0'
    #     expected: '1'
    # Looks like you failed 2 tests of 3.
    t/70_Helper/45_bulk_cxn_errors.t .............. Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/3 subtests 
    t/70_Helper/50_scroll.t ....................... skipped: No Elasticsearch test node available
    t/70_Helper/60_reindex.t ...................... skipped: No Elasticsearch test node available
    t/90_Client_Spec/00_print_version.t ........... skipped: No Elasticsearch test node available
    t/author-eol.t ................................ skipped: these tests are for testing by the author
    t/author-no-tabs.t ............................ skipped: these tests are for testing by the author
    t/release-pod-syntax.t ........................ skipped: these tests are for release candidate testing

    Test Summary Report
    -------------------
    t/70_Helper/45_bulk_cxn_errors.t            (Wstat: 512 Tests: 3 Failed: 2)
      Failed tests:  2-3
      Non-zero exit status: 2
    Files=70, Tests=423,  8 wallclock secs ( 0.24 usr  0.04 sys +  7.26 cusr  0.68 csys =  8.22 CPU)
    Result: FAIL
    Failed 1/70 test programs. 2/423 subtests failed.
    make: *** [test_dynamic] Error 255
      DRTECH/Search-Elasticsearch-1.20.tar.gz
      /usr/bin/make test -- NOT OK
    //hint// to see the cpan-testers results for installing this module, try:
      reports DRTECH/Search-Elasticsearch-1.20.tar.gz
    Running make install
      make test had returned bad status, won't install without force

    --------------------------------

**Comment by clintongormley** [comment] 2015-06-26 12:07
Closing as duplicate of #69

**Closed by clintongormley** 2015-06-26 12:07 UTC
